# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Test2' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'

end

target 'Test2Tests' do

end

